POST http://localhost:3001/api/blogs HTTP/1.1
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMTIzIiwiaWQiOiI2MTNlODFmNjU3OWYzZjFkNzk3N2VhYzAiLCJpYXQiOjE2MzE0ODY0NjgsImV4cCI6MTYzMTQ5MDA2OH0.3zZcb-eXAPZRLvVmm62x6wxlEwknrj4X0-6rS_ZZbZM

{
    "title": "Blog 11111",
    "author": "admin123",
    "url": "http://",
    "likes": 1,
    "userId": "613e81f6579f3f1d7977eac0"
}